{
 "title": "MikroTik-Switch Ovetview",
 "tags": [
  "mikrotik",
  "switch",
  "CRS112",
  "snmp exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Switch Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"mikrotik-switch\"} / 100"
    }
   ]
  },
  {
   "title": "Total Inbound Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ifInOctets{job=\"mikrotik-switch\", ifDescr!=\"bridge1\"}[5m])) * 8"
    }
   ]
  },
  {
   "title": "Total Outbound Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ifOutOctets{job=\"mikrotik-switch\", ifDescr!=\"bridge1\"}[5m])) * 8"
    }
   ]
  },
  {
   "title": "Ethernet Ports Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"mikrotik-switch\", ifDescr=~\"ether.*\"}"
    }
   ]
  },
  {
   "title": "SFP Ports Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"mikrotik-switch\", ifDescr=~\"sfp.*\"}"
    }
   ]
  },
  {
   "title": "Ethernet Ports Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInOctets{job=\"mikrotik-switch\", ifDescr=~\"ether.*\"}[5m]) * 8",
     "legendFormat": "In {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutOctets{job=\"mikrotik-switch\", ifDescr=~\"ether.*\"}[5m]) * 8",
     "legendFormat": "Out {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SFP Ports Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInOctets{job=\"mikrotik-switch\", ifDescr=~\"sfp.*\"}[5m]) * 8",
     "legendFormat": "In {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutOctets{job=\"mikrotik-switch\", ifDescr=~\"sfp.*\"}[5m]) * 8",
     "legendFormat": "Out {{ifDescr}}"
    }
   ]
  }
 ]
}