{
 "title": "Synology NAS Overview",
 "tags": [
  "synology",
  "DS224+",
  "snmp exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NAS UP Status",
   "type": "bargauge",
   "description": "1 = NAS is reachable; 0 = down/unreachable. Basic health check.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.10.10\", job=\"synology-nas\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "CPU utilization percentage of the Synology NAS. Shows how busy the NAS is.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "synology_cpu_load{instance=\"192.168.10.10\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "synology_storage_used{instance=\"192.168.10.10\", hrStorageDescr=\"Physical memory\"}\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "synology_storage_size{instance=\"192.168.10.10\", hrStorageDescr=\"Available memory\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Total Size",
   "type": "piechart",
   "description": "synology_storage_size{instance=\"192.168.10.10\"}",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synology_storage_size{instance=\"192.168.10.10\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "piechart",
   "description": "Description: How much space is currently used per volume or memory/storage type. Labels like hrStorageDescr show which partition or memory type.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synology_storage_used{instance=\"192.168.10.10\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNMP Packets Sent",
   "type": "timeseries",
   "description": "Number of SNMP packets sent to the NAS during scrapes.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "snmp_scrape_packets_sent{instance=\"192.168.10.10\", module=\"synology\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}